 --- Init ---
MyPythonBot
 --- Bot used 70 milliseconds ---
-----------------------------------------------------------------------------
 --- Frame #1 ---
Traceback (most recent call last):
 --- Bot used 2 milliseconds ---
ERRORED!
Response received (if any):
Traceback (most recent call last):
 --- Bot was killed. Below is the rest of its output (if any): ---
  File "MyBot.py", line 121, in <module>
    hlt.send_frame(moves)
  File "/Users/Catie/PycharmProjects/Halite/hlt.py", line 111, in send_frame
    send_string(' '.join(str(move.square.x) + ' ' + str(move.square.y) + ' ' + str(translate_cardinal(move.direction)) for move in moves))
  File "/Users/Catie/PycharmProjects/Halite/hlt.py", line 111, in <genexpr>
    send_string(' '.join(str(move.square.x) + ' ' + str(move.square.y) + ' ' + str(translate_cardinal(move.direction)) for move in moves))
  File "/Users/Catie/PycharmProjects/Halite/hlt.py", line 107, in translate_cardinal
    return (direction + 1) % 5
TypeError: can only concatenate tuple (not "int") to tuple

 --- End bot output ---